name:                pixie
version:             0.1.0.0
github:              "rkaippully/pixie"
license:             BSD3
author:              "Raghu Kaippully"
maintainer:          "rkaippully@gmail.com"
copyright:           "Raghu Kaippully"

extra-source-files:
- README.org

description:         Please see the README on GitHub at <https://github.com/rkaippully/pixie#readme>

dependencies:
  - base >= 4.7 && < 5
  - relude

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - DerivingStrategies

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: lib
  dependencies:
    - megaparsec

executables:
  pasm:
    main:                Main.hs
    source-dirs:         pasm/app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pixie

tests:
  pasm-test:
    main:                Spec.hs
    source-dirs:         pasm/test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pixie
